require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


target 'cyllid' do
  config = use_native_modules!

  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  use_react_native!(:path => config["reactNativePath"])
  target 'cyllidTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'cyllid-tvOS' do
  # Pods for cyllid-tvOS

  target 'cyllid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
